# production environment
FROM node:16.15.0
# Create app directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
# Create env variables
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ARG GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
ENV GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
ARG VITE_BACKEND_URL=${VITE_BACKEND_URL}
ENV VITE_BACKEND_URL=${VITE_BACKEND_URL}
ARG VITE_IMAGES_URL=${VITE_IMAGES_URL}
ENV VITE_IMAGES_URL=${VITE_IMAGES_URL}
ARG APP_PORT=${APP_PORT}
ENV APP_PORT=${APP_PORT}
ARG DB_HOST=${DB_HOST}
ENV DB_HOST=${DB_HOST}
ARG DB_USER=${DB_USER}
ENV DB_USER=${DB_USER}
ARG DB_PASSWORD=${DB_PASSWORD}
ENV DB_PASSWORD=${DB_PASSWORD}
ARG DB_NAME=${DB_NAME}
ENV DB_NAME=${DB_NAME}
ARG FRONTEND_URL=${FRONTEND_URL}
ENV FRONTEND_URL=${FRONTEND_URL}
ARG ACCESS_JWT_SECRET=${ACCESS_JWT_SECRET}
ENV ACCESS_JWT_SECRET=${ACCESS_JWT_SECRET}
ARG ACCESS_JWT_EXPIRESIN=${ACCESS_JWT_EXPIRESIN}
ENV ACCESS_JWT_EXPIRESIN=${ACCESS_JWT_EXPIRESIN}
ARG ACCESS_JWT_COOKIE_MAXAGE=${ACCESS_JWT_COOKIE_MAXAGE}
ENV ACCESS_JWT_COOKIE_MAXAGE=${ACCESS_JWT_COOKIE_MAXAGE}
ARG ACCESS_JWT_SECURE=${ACCESS_JWT_SECURE}
ENV ACCESS_JWT_SECURE=${ACCESS_JWT_SECURE}
ARG RESET_PASSWORD_JWT_SECRET=${RESET_PASSWORD_JWT_SECRET}
ENV RESET_PASSWORD_JWT_SECRET=${RESET_PASSWORD_JWT_SECRET}
ARG RESET_PASSWORD_JWT_EXPIRESIN=${RESET_PASSWORD_JWT_EXPIRESIN}
ENV RESET_PASSWORD_JWT_EXPIRESIN=${RESET_PASSWORD_JWT_EXPIRESIN}
ARG RESET_PASSWORD_JWT_SECURE=${RESET_PASSWORD_JWT_SECURE}
ENV RESET_PASSWORD_JWT_SECURE=${RESET_PASSWORD_JWT_SECURE}
ARG RESET_PASSWORD_JWT_COOKIE_MAXAGE=${RESET_PASSWORD_JWT_COOKIE_MAXAGE}
ENV RESET_PASSWORD_JWT_COOKIE_MAXAGE=${RESET_PASSWORD_JWT_COOKIE_MAXAGE}
ARG EMAIL_HOST=${EMAIL_HOST}
ENV EMAIL_HOST=${EMAIL_HOST}
ARG EMAIL_PORT=${EMAIL_PORT}
ENV EMAIL_PORT=${EMAIL_PORT}
ARG EMAIL_SECURE=${EMAIL_SECURE}
ENV EMAIL_SECURE=${EMAIL_SECURE}
ARG EMAIL_USER=${EMAIL_USER}
ENV EMAIL_USER=${EMAIL_USER}
ARG EMAIL_PASS=${EMAIL_PASS}
ENV EMAIL_PASS=${EMAIL_PASS}
ARG EMAIL_REPLY=${EMAIL_REPLY}
ENV EMAIL_REPLY=${EMAIL_REPLY}

COPY ./ /usr/src/app
RUN npm install -g pnpm
# Create front app
RUN cd ./frontend && pnpm i && pnpm build
RUN mkdir -p ./frontend/dist/src && cp -r ./frontend/src/assets ./frontend/dist/src
RUN cp ./frontend/robots.txt ./frontend/dist/
# Create back app
RUN cd ./backend && pnpm i --prod

# expose full app on APP_PORT
EXPOSE ${APP_PORT}
CMD ["node", "backend/index.js"]
